services:
  - type: web
    name: telegram-order-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 wsgi:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
    region: frankfurt
    healthCheckPath: /
