databases:
  - name: telegram-bot-db
    databaseName: telegram_bot
    user: telegram_bot_user
    plan: free

services:
  - type: web
    name: telegram-order-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
