services:
  - type: web
    name: telegram-order-bot
    dockerfile: Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
    plan: free
    region: frankfurt
    healthCheckPath: /
    autoDeploy: true
